# Generated by Django 2.1.7 on 2019-03-02 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Captain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('geo_name', models.CharField(blank=True, max_length=255)),
                ('latitude', models.IntegerField(blank=True)),
                ('longitude', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jv_dj_app.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('flag', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=512)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True)),
                ('bought_sold', models.CharField(choices=[('bought', 'bought'), ('sold', 'sold')], default='bought', max_length=255)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jv_dj_app.Item')),
                ('port_visit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jv_dj_app.PortVisit')),
            ],
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('ship', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jv_dj_app.Ship')),
                ('ship_captain', models.ManyToManyField(blank=True, to='jv_dj_app.Captain')),
                ('sources', models.ManyToManyField(blank=True, to='jv_dj_app.Source')),
            ],
        ),
        migrations.AddField(
            model_name='portvisit',
            name='voyage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jv_dj_app.Voyage'),
        ),
    ]
