# Generated by Django 2.1.7 on 2019-03-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jv_dj_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='captain',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portvisit',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ship',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
