# Generated by Django 2.1.7 on 2019-03-03 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jv_dj_app', '0002_auto_20190303_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jv_dj_app.Location')),
            ],
        ),
        migrations.RenameField(
            model_name='voyage',
            old_name='ship_captain',
            new_name='captain',
        ),
        migrations.RemoveField(
            model_name='portvisit',
            name='location',
        ),
        migrations.AddField(
            model_name='portvisit',
            name='end_port',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='portvisit',
            name='start_port',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='voyage',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyage',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portvisit',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='portvisit',
            name='start_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='ship',
            name='flag',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ship',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='portvisit',
            name='port',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jv_dj_app.Port'),
        ),
        migrations.AddField(
            model_name='ship',
            name='home_port',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jv_dj_app.Port'),
        ),
    ]
